markdown: kramdown
rouge: true
future: true
lsi: false

extensions:	
 - autolink      # greedily urlify links
 - footnotes     # footnotes
 - smart         # typographic substitutions with SmartyPants
 
author: Saptarshi Guha
username: saptarshiguha
email: saptarshi.guha@gmail.com

accounts:
    github: https://github.com/saptarshiguha
    linkedin: http://linkedin.com/saptarshiguha
    google: https://plus.google.com/115887938173387570339/

name: aajikali
description: that often thought yet rarely written
baseurl: /blog
#url: https://people.mozilla.com/~sguha/blog
url: /Users/sguha/saptarshiguha.github.io/_site/
mybase: ./

tags:
- jekyll
- code

kramdown:
   enable_coderay: true
   toc_levels: 2..6
   use_coderay: true

      
      